//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Payroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_Sub_Category
    {
        public int Asset_Sub_Category_ID { get; set; }
        public string Sub_Category_Code { get; set; }
        public string Sub_Category_Name { get; set; }
        public Nullable<int> Asset_Category_ID { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> SubAsset_Purchase_Date { get; set; }
        public Nullable<System.DateTime> SubAsset_Warranty_Date { get; set; }
        public Nullable<decimal> SubAsset_Value { get; set; }
        public Nullable<decimal> SubAsset_Recovery_Value { get; set; }
        public string SubAsset_ModelNo { get; set; }
        public string SubAsset_SerialNo { get; set; }
    
        public virtual Asset_Category Asset_Category { get; set; }
    }
}
