//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Payroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityMaster
    {
        public int City_ID { get; set; }
        public string City_Name { get; set; }
        public string City_Code { get; set; }
        public Nullable<int> State_ID { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
    
        public virtual StateMaster StateMaster { get; set; }
    }
}
