//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Payroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Assets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company_Assets()
        {
            this.Employee_Allocate_Asstets = new HashSet<Employee_Allocate_Asstets>();
        }
    
        public int Company_Assets_ID { get; set; }
        public string Asset_Category { get; set; }
        public string Asset_Sub_Category { get; set; }
        public string Asset_Name { get; set; }
        public string Asset_Working_Status { get; set; }
        public Nullable<decimal> Asset_Value { get; set; }
        public Nullable<decimal> Recoverable_Value { get; set; }
        public Nullable<System.DateTime> Purchase_Date { get; set; }
        public Nullable<System.DateTime> Warranty_Date { get; set; }
        public string Serial_No { get; set; }
        public string Part_No { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Allocate_Asstets> Employee_Allocate_Asstets { get; set; }
    }
}
