//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Payroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Educational_Background
    {
        public int ID { get; set; }
        public Nullable<int> Emp_No { get; set; }
        public string Educational_Qualification { get; set; }
        public string Specialization { get; set; }
        public Nullable<System.DateTime> From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
        public Nullable<System.DateTime> Year_Of_Passing { get; set; }
        public Nullable<decimal> Mark_Percentage { get; set; }
        public string Grade { get; set; }
        public byte[] Attachment { get; set; }
        public string Attachment_Flag { get; set; }
        public string Flag { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
    }
}
