//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Payroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Employee_Advance = new HashSet<Employee_Advance>();
            this.Employee_Allocate_Asstets = new HashSet<Employee_Allocate_Asstets>();
            this.Employee_Attandance = new HashSet<Employee_Attandance>();
            this.Employee_Bonus = new HashSet<Employee_Bonus>();
            this.Employee_Gratutity = new HashSet<Employee_Gratutity>();
            this.Employee_Leave_Enchasement = new HashSet<Employee_Leave_Enchasement>();
            this.Employee_Recover_Asstets = new HashSet<Employee_Recover_Asstets>();
            this.Employee_Reimbursement = new HashSet<Employee_Reimbursement>();
            this.Employee_Salary = new HashSet<Employee_Salary>();
            this.Employee_Salary_Account = new HashSet<Employee_Salary_Account>();
            this.Employee_Salary_Group_Mapping = new HashSet<Employee_Salary_Group_Mapping>();
            this.Employee_Salary_Offer_Gross = new HashSet<Employee_Salary_Offer_Gross>();
            this.Employee_TDS = new HashSet<Employee_TDS>();
            this.Financial_Institute_Employee_Mapping = new HashSet<Financial_Institute_Employee_Mapping>();
            this.Monthly_Salary_Roaster = new HashSet<Monthly_Salary_Roaster>();
            this.Pan_Card = new HashSet<Pan_Card>();
        }
    
        public int Emp_No { get; set; }
        public string Emp_FirstName { get; set; }
        public string Emp_MiddleName { get; set; }
        public string Emp_LastName { get; set; }
        public Nullable<System.DateTime> Emp_Dob { get; set; }
        public Nullable<System.DateTime> Emp_Doj { get; set; }
        public Nullable<int> Grade_ID { get; set; }
        public Nullable<int> Designation_ID { get; set; }
        public Nullable<int> Department_ID { get; set; }
        public Nullable<int> Sub_Department_ID { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public string Employee_Group_Code_Name { get; set; }
        public Nullable<int> Machine_Details_ID { get; set; }
        public string Machine_Punching_Card_No { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Advance> Employee_Advance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Allocate_Asstets> Employee_Allocate_Asstets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Attandance> Employee_Attandance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Bonus> Employee_Bonus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Gratutity> Employee_Gratutity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Leave_Enchasement> Employee_Leave_Enchasement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Recover_Asstets> Employee_Recover_Asstets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Reimbursement> Employee_Reimbursement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Salary> Employee_Salary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Salary_Account> Employee_Salary_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Salary_Group_Mapping> Employee_Salary_Group_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Salary_Offer_Gross> Employee_Salary_Offer_Gross { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_TDS> Employee_TDS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financial_Institute_Employee_Mapping> Financial_Institute_Employee_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Monthly_Salary_Roaster> Monthly_Salary_Roaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pan_Card> Pan_Card { get; set; }
    }
}
