//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Payroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Allocate_Asstets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee_Allocate_Asstets()
        {
            this.Employee_Recover_Asstets = new HashSet<Employee_Recover_Asstets>();
        }
    
        public int Employee_Allocate_Asstets_ID { get; set; }
        public Nullable<int> Emp_No { get; set; }
        public Nullable<int> Company_Assets_ID { get; set; }
        public Nullable<System.DateTime> Issuable_Date { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
    
        public virtual Company_Assets Company_Assets { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Recover_Asstets> Employee_Recover_Asstets { get; set; }
    }
}
