//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Payroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financial_Institute_Employee_Mapping
    {
        public int Mapping_ID { get; set; }
        public Nullable<int> Financial_Institution_ID { get; set; }
        public Nullable<int> Emp_No { get; set; }
        public string Address_Finacial_Institute { get; set; }
        public string Branch { get; set; }
        public string PinCode { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Financial_Institution Financial_Institution { get; set; }
    }
}
