//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Payroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gratutity_Setting
    {
        public int Gratutity_Setting_ID { get; set; }
        public Nullable<decimal> Maximum_Gratutity_Limit { get; set; }
        public string Min_Eligibility_Year_for_Gratutity { get; set; }
        public string Gratutity_Calculated_On { get; set; }
        public Nullable<int> Fiancial_Year_ID { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
    
        public virtual Financial_Year Financial_Year { get; set; }
    }
}
