//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Payroll.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HR_PayrollEntities : DbContext
    {
        public HR_PayrollEntities()
            : base("name=HR_PayrollEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asset_Category> Asset_Category { get; set; }
        public virtual DbSet<Asset_Status> Asset_Status { get; set; }
        public virtual DbSet<Asset_Sub_Category> Asset_Sub_Category { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<CityMaster> CityMasters { get; set; }
        public virtual DbSet<Communication_Address> Communication_Address { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Company_Assets> Company_Assets { get; set; }
        public virtual DbSet<Dependent> Dependents { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Educational_Background> Educational_Background { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_Advance> Employee_Advance { get; set; }
        public virtual DbSet<Employee_Allocate_Asstets> Employee_Allocate_Asstets { get; set; }
        public virtual DbSet<Employee_Attandance> Employee_Attandance { get; set; }
        public virtual DbSet<Employee_Bonus> Employee_Bonus { get; set; }
        public virtual DbSet<Employee_Gratutity> Employee_Gratutity { get; set; }
        public virtual DbSet<Employee_Leave_Enchasement> Employee_Leave_Enchasement { get; set; }
        public virtual DbSet<Employee_Recover_Asstets> Employee_Recover_Asstets { get; set; }
        public virtual DbSet<Employee_Reimbursement> Employee_Reimbursement { get; set; }
        public virtual DbSet<Employee_Salary> Employee_Salary { get; set; }
        public virtual DbSet<Employee_Salary_Account> Employee_Salary_Account { get; set; }
        public virtual DbSet<Employee_Salary_Group_Mapping> Employee_Salary_Group_Mapping { get; set; }
        public virtual DbSet<Employee_Salary_Offer_Gross> Employee_Salary_Offer_Gross { get; set; }
        public virtual DbSet<Employee_TDS> Employee_TDS { get; set; }
        public virtual DbSet<ESI_Rate> ESI_Rate { get; set; }
        public virtual DbSet<Experince_Letter_Previous_Company> Experince_Letter_Previous_Company { get; set; }
        public virtual DbSet<Financial_Institute_Employee_Mapping> Financial_Institute_Employee_Mapping { get; set; }
        public virtual DbSet<Financial_Institution> Financial_Institution { get; set; }
        public virtual DbSet<Financial_Year> Financial_Year { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<Gratutity_Setting> Gratutity_Setting { get; set; }
        public virtual DbSet<Health_Insurance> Health_Insurance { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Marriage_Certificate_Proof> Marriage_Certificate_Proof { get; set; }
        public virtual DbSet<Monthly_Salary_Roaster> Monthly_Salary_Roaster { get; set; }
        public virtual DbSet<NationalityMaster> NationalityMasters { get; set; }
        public virtual DbSet<Nominee_Details> Nominee_Details { get; set; }
        public virtual DbSet<Pan_Card> Pan_Card { get; set; }
        public virtual DbSet<Passport> Passports { get; set; }
        public virtual DbSet<Permanent_Address> Permanent_Address { get; set; }
        public virtual DbSet<PF_Rate> PF_Rate { get; set; }
        public virtual DbSet<Professional_Certificate> Professional_Certificate { get; set; }
        public virtual DbSet<Relation> Relations { get; set; }
        public virtual DbSet<Salary_Group> Salary_Group { get; set; }
        public virtual DbSet<Salary_Group_Type_Master> Salary_Group_Type_Master { get; set; }
        public virtual DbSet<Salary_Head> Salary_Head { get; set; }
        public virtual DbSet<Salary_Head_Type> Salary_Head_Type { get; set; }
        public virtual DbSet<Salary_Slip_Previous_Company> Salary_Slip_Previous_Company { get; set; }
        public virtual DbSet<Skill_Set> Skill_Set { get; set; }
        public virtual DbSet<StateMaster> StateMasters { get; set; }
        public virtual DbSet<Sub_Department> Sub_Department { get; set; }
        public virtual DbSet<CountryMaster> CountryMasters { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
    }
}
