//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Payroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marriage_Certificate_Proof
    {
        public int ID { get; set; }
        public Nullable<int> Emp_No { get; set; }
        public string Spouce_Name { get; set; }
        public Nullable<System.DateTime> Data_Of_Marriage { get; set; }
        public string Marriage_Certificate_Ref_No { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public byte[] Attachment { get; set; }
        public string Attachment_Flag { get; set; }
    }
}
