//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Payroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monthly_Salary_Roaster
    {
        public int Monthly_Salary_Roaster_ID { get; set; }
        public Nullable<int> Emp_No { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Dept_Name { get; set; }
        public Nullable<int> No_Of_Working_Days { get; set; }
        public Nullable<int> No_Pay_days { get; set; }
        public Nullable<int> No_Of_Attendance { get; set; }
        public Nullable<decimal> Gross_Salary { get; set; }
        public Nullable<decimal> Basic_Amount_Earning { get; set; }
        public Nullable<decimal> Conveyance_Allowance_Earning { get; set; }
        public Nullable<decimal> HRA_Earning { get; set; }
        public Nullable<decimal> Medical_Allowance_Earning { get; set; }
        public Nullable<decimal> Travelling_Allowance_Earning { get; set; }
        public Nullable<decimal> Money_Advance_Earning { get; set; }
        public Nullable<decimal> Other_Reimbursement_Amount_Earning { get; set; }
        public Nullable<decimal> Bouns_Earning { get; set; }
        public Nullable<decimal> Gratutity_Earning { get; set; }
        public Nullable<decimal> Leave_Enchasment_Earning { get; set; }
        public Nullable<decimal> Food_Coupon_Deduction { get; set; }
        public Nullable<decimal> PF_Deduction { get; set; }
        public Nullable<decimal> ESI_Deduction { get; set; }
        public Nullable<decimal> TDS_Deduction { get; set; }
        public Nullable<decimal> Money_Advance_Recovery_Deduction { get; set; }
        public Nullable<decimal> Asset_Recovery_Deduction { get; set; }
        public Nullable<decimal> Gross_Deduction { get; set; }
        public Nullable<decimal> Gross_Earning { get; set; }
        public Nullable<decimal> Net_Payable { get; set; }
        public Nullable<int> Salary_Year { get; set; }
        public Nullable<int> Salary_Month { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
